version: '3'
services:
  web:
    container_name: checkout-web
    build: .
    ports:
        - "5005:5000"
    depends_on:
        - postgres_database
  postgres_database:
    container_name: postgres_database
    image: postgres:latest
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./dbscripts/init.sql :/docker-entrypoint-initdb.d/init.sql